import { pgEnum } from "drizzle-orm/pg-core";

/**
 * Debt lifecycle status.
 * - active:   Debt is currently being tracked and actively repaid.
 * - paused:   User temporarily paused tracking or calculations on this account.
 * - settled:  The holy grail — the debt has been fully paid off to 0.
 * - archived: Debt was manually hidden or archived by the user without deleting history.
 */
export const debtStatusEnum = pgEnum("debt_status", [
  "active",
  "paused",
  "settled",
  "archived",
]);

/**
 * Ledger entry types.
 * Fully expanded now to prevent painful PostgreSQL type migrations later.
 * - opening:    The initial balance when a debt is first created.
 * - payment:    User recorded a repayment (reduces balance).
 * - interest:   Interest accrued on the debt (increases balance).
 * - fee:        Late fees or structural penalties applied (increases balance).
 * - adjustment: Manual balance correction with a required auditing note.
 * - reversal:   An entry that voids out a previous transaction record.
 */
export const ledgerEntryTypeEnum = pgEnum("ledger_entry_type", [
  "opening",
  "payment",
  "interest",
  "fee",
  "adjustment",
  "reversal",
]);

/**
 * System origin of who or what generated a ledger entry.
 * - user:   Manually created by the authenticated user.
 * - system: Created automatically by the application (e.g., initial opening balance).
 * - job:    Generated by a background execution system (e.g., automated interest calculation via Trigger.dev).
 */
export const ledgerRecordedByEnum = pgEnum("ledger_recorded_by", [
  "user",
  "system",
  "job",
]);

/**
 * Subscription plan tiers to handle our Freemium MVP strategy.
 * - free: Limited to a maximum of 3 active debts.
 * - pro:  Unlimited debts and access to premium tools (strategies, analytics).
 */

export const subscriptionTierEnum = pgEnum("subscription_tier", [
  "free",
  "pro",
]);

// Add this right next to your subscriptionTierEnum
export const billingPlanEnum = pgEnum("billing_plan", [
  "pro",
  // "enterprise", "family" can easily be added here later without migrating existing structures
]);

// Update this to include the missing "unpaid" state from Stripe/Paystack models
export const subscriptionStatusEnum = pgEnum("subscription_status", [
  "active",
  "canceled",
  "past_due",
  "trialing",
  "incomplete",
  "unpaid",
]);

export const paymentProviderEnum = pgEnum("payment_provider", [
  "stripe",
  "paystack",
]);

// Update your existing reminderStatusEnum to include the "retrying" state
export const reminderStatusEnum = pgEnum("reminder_status", [
  "pending",
  "retrying",
  "sent",
  "failed",
  "canceled",
]);

// Add a new notification channel enum to support future SMS or WhatsApp scaling paths
export const notificationChannelEnum = pgEnum("notification_channel", [
  "email",
  "push",
  "sms",
]);

export const reminderTypeEnum = pgEnum("reminder_type", [
  "payment_due",
  "payment_overdue",
  "general_notification",
]);

// ─── DRIZZLE TYPE INFERENCE EXPORTS ──────────────────────────────────────────
// Infers clean, type-safe strings directly from the runtime schema arrays.
// Use these across actions, services, and components.

export type DebtStatus = (typeof debtStatusEnum.enumValues)[number];
export type LedgerEntryType = (typeof ledgerEntryTypeEnum.enumValues)[number];
export type LedgerRecordedBy = (typeof ledgerRecordedByEnum.enumValues)[number];
export type SubscriptionStatus =
  (typeof subscriptionStatusEnum.enumValues)[number];
export type SubscriptionTier = (typeof subscriptionTierEnum.enumValues)[number];
export type BillingPlan = (typeof billingPlanEnum.enumValues)[number];
export type PaymentProvider = (typeof paymentProviderEnum.enumValues)[number];
export type ReminderStatus = (typeof reminderStatusEnum.enumValues)[number];
export type NotificationChannel =
  (typeof notificationChannelEnum.enumValues)[number];
export type ReminderType = (typeof reminderTypeEnum.enumValues)[number];
